import Navbar from '../navbar'
import { Box } from '@chakra-ui/react'
import Head from 'next/head'

const Main = ({ children }: React.PropsWithChildren<{}>) => {
    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <main>
                {children}
            </main>

            <footer>
                <p>Footer Here</p>
            </footer>
        </Box>
    )
}

export default Main